services:
  admin-frontend:
    build:
      context: ./apps/admin-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  public-frontend:
    build:
      context: ./apps/public-frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  backend-api:
    build:
      context: ./apps/backend-api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      - db
