const SafeIcon = () => (
  <svg
    width="32"
    height="32"
    viewBox="0 0 32 32"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="8.89"
      y="9.66"
      width="14.21"
      height="12.68"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <rect
      x="10.39"
      y="11.21"
      width="11.16"
      height="9.62"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="10.39"
      y1="13.35"
      x2="8.89"
      y2="13.35"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="10.39"
      y1="14.9"
      x2="8.89"
      y2="14.9"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="10.39"
      y1="17.12"
      x2="8.89"
      y2="17.12"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="10.39"
      y1="18.67"
      x2="8.89"
      y2="18.67"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <circle
      cx="15.26"
      cy="16.02"
      r="2.57"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="15.26"
      y1="13.46"
      x2="15.26"
      y2="14.53"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="15.26"
      y1="18.59"
      x2="15.26"
      y2="17.52"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="12.69"
      y1="16.02"
      x2="13.76"
      y2="16.02"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <line
      x1="17.82"
      y1="16.02"
      x2="16.75"
      y2="16.02"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
    <path
      d="M20.46,14.07h1.1v3.74h-1.1c-.42,0-.77-.34-.77-.77v-2.2c0-.42.34-.77.77-.77Z"
      fill="none"
      stroke="#cafffa"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth=".8"
    />
  </svg>
);
export default SafeIcon;
